---
- name: get the arm32 telegraf tar file
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf-{{ telegraf_ver }}_linux_armhf.tar.gz
    dest: "/root/telegraf-{{ telegraf_ver }}_linux_armhf.tar.gz"
  when: ansible_architecture == "aarch" or ansible_architecture == "aarch64"
  register: ttar

- name:     add telegraf group
  group:
    name:   telegraf
    system: yes

- name:     add telegraf user
  user:
    name:   telegraf
    group:  telegraf
    home:   /var/lib/telegraf
    system: yes

- block:
  - name: tar file
    unarchive:
      src: "/root/telegraf-{{ telegraf_ver }}_linux_armhf.tar.gz"
      dest: /
      remote_src: yes
      extra_opts:
        - "--strip-components=2"

  - name: enable systemd startup
    file:
      src: /usr/lib/telegraf/scripts/telegraf.service
      dest: /etc/systemd/system/telegraf.service
      state: link

  - name: refresh systemd
    systemd:
      name: telegraf
      state: enabled
      daemon_reload: yes
  when: ttar.changed
